# Dicionários de renomeação (nome original -> nome novo compacto), gerados automaticamente
# a partir do dicionario_colunas.xlsx. Um dict por aba.

rename_maps = {}

rename_maps["T10_11_14_15_17"] = {
    "Nome completo": "nome_completo",
    "Aprovadas": "status_aprovacao",
    "Como você se identifica": "genero",
    "Você faz parte da comunidade LGBTQIA+ ?": "lgbtqia",
    "Como você se identifica 2": "raca_etnia",
    "Idade (Somente números)": "idade",
    "Você é uma pessoa com deficiência ? ": "pcd",
    "Caso sim para a pergunta acima, nos conte sobre, principalmente se ela altera o seu aprendizado. Caso não, deixe em branco esta pergunta.": "pcd_detalhe",
    "Caso sim para deficiência, há necessidade de adaptações para atividades de aprendizado ou atividades remotas por computador ? ": "pcd_necessita_adaptacao",
    "Grau de Escolaridade": "escolaridade",
    "Estado que mora:": "estado_residencia",
    "Cidade em que mora:": "cidade_residencia",
    "Como conheceu o Meninas In Tech e chegou até aqui ?": "como_conheceu_mulheres_in_tech",
    "Você já fez outro processo seletivo ou programa na Fly ? ": "processo_seletivo_anterior",
    "Se sim para a pergunta acima, qual foi o processo ou programa ?": "processo_seletivo_anterior_detalhe",
    "Quantas pessoas moram na sua casa?": "qtd_pessoas_casa",
    "Renda familiar por pessoa:": "renda_familiar_pessoa",
    "Qual a sua renda ? ": "renda_propria",
    "Sua renda é a principal fonte de renda de sua casa ? ": "renda_principal_fonte_casa",
    "Atualmente você está:": "situacao_profissional_atual",
    "Como funciona a situação financeira na sua casa ? (Comente sobre os moradores, as colocações profissionais, etc.)": "situacao_financeira_casa",
    "Tem interesse em desenvolvimento de Web?": "interesse_dev_web",
    "Possui computador?": "possui_computador",
    "Possui acesso ao Wi-Fi/Internet?": "possui_wifi",
    "Você tem disponibilidade de quata-feira 19hs-21:00hs por 6 meses?": "disponibilidade_quarta_noite",
    "Você tem disponibilidade de uma vez na semana, de 1 a 2 horas, fazer uma mentoria?": "disponibilidade_mentoria_semanal",
    "Qual sua disponibilidade verdadeiramente de tempo para estudar e dedicar no curso:": "disponibilidade_tempo_estudo",
    "Turma": "turma",
    "Unnamed: 28": "coluna_vazia"
}

rename_maps["T12"] = {
    "Nome completo": "nome_completo",
    "Etnia: Como você se identifica": "raca_etnia",
    "Você é uma pessoa com deficiência?": "pcd",
    "Você é uma pessoa com deficiência? Caso, sim, nos conte sobre, principalmente se ela altera o seu aprendizado. Caso não, deixe em branco esta pergunta.": "pcd_detalhe",
    "Caso sim para a pergunta acima, nos conte sobre, principalmente se ela altera o seu aprendizado e como. Caso não, deixe em branco esta pergunta.": "pcd_detalhe",
    "Você é uma pessoa refugiada?": "refugiada_imigrante",
    "Caso sim, de qual pais você é?": "refugiada_pais",
    "Grau de Escolaridade": "escolaridade",
    "Estado que mora:": "estado_residencia",
    "Em qual cidade reside": "cidade_residencia",
    "Como conheceu o Mulheres In Tech e chegou até aqui?": "como_conheceu_mulheres_in_tech",
    "Você já fez outro processo seletivo ou programa na Fly? Se sim, qual?": "processo_seletivo_anterior",
    "Quantas pessoas moram na sua casa? (somente números)": "qtd_pessoas_casa",
    "Renda familiar por pessoa:": "renda_familiar_pessoa",
    "Atualmente você está:": "situacao_profissional_atual",
    "Como funciona a situação financeira na sua casa?": "situacao_financeira_casa",
    "Tem interesse em IA & Gestão: Mulheres Pretas Líderes?": "interesse_ia_gestao",
    "Justifique": "justificativa_interesse",
    "Possui computador em casa?": "possui_computador",
    "Possui acesso ao Wi-Fi/Internet?": "possui_wifi",
    "O programa inclui mentorias semanais com mulheres que já trabalham na área para lhe ajudar com o conhecimento socioemocional e técnico do programa, como você se vê sendo uma mentorada? Como seria a mentoria ideal para você?": "expectativa_mentoria",
    "É esperado que você estude 10 horas semanais (2h por dia) e, após estudar o conteúdo, conforme surgirem dúvidas, chamar a mentora para lhe ajudar. Como você se percebe pedindo ajuda na sua vida?": "percepcao_pedir_ajuda",
    "Você vai ter que estudar 2h por dia, de forma assíncrona na plataforma. Conte um caso onde você foi autodidata para aprender alguma coisa antes e deu certo :)": "experiencia_autodidata",
    "O programa tem uma duração de 5 meses, 20 semanas, conte para nós uma experiência positiva onde você tenha iniciado algo e chegado até o fim, por que você acha que conseguiu chegar até o fim da mesma?": "experiencia_positiva_conclusao",
    "Agora, conte para nós uma experiência negativa onde você tenha iniciado algo e não tenha chegado até o fim, e, por que você acha que não conseguiu chegar até o fim da mesma?": "experiencia_negativa_nao_conclusao",
    "O que acha que mudou de uma a experiência a outra? Porque na primeira, sim, e na segunda não?": "diferenca_entre_experiencias",
    "O que te leva a acreditar que você vai chegar no fim desse programa?": "confianca_concluir_programa",
    "A gente sabe que a vida é bem corrida para todos, qual sua disponibilidade verdadeira de tempo para estudar e dedicar no curso:": "disponibilidade_tempo_estudo",
    "Descreva como é uma semana na sua vida": "rotina_semanal_descricao",
    "Descreva como vai encaixar às 10h de estudo semanal nessa semana na sua vida, se for aprovada": "encaixe_horas_estudo_rotina",
    "Se nós lhe perguntássemos, por que deveríamos escolher você diante de outras candidatas, o que você responderia se não tivesse vergonha de responder?": "motivo_escolha_candidata",
    "Para receber o certificado de Formatura do Mulheres in Tech da Fly Educação você precisa preencher os seguintes critérios:\n- 75% de presença nas aulas socioemocionais, ao vivo\n- 100% de conclusão nas aulas científicas, via plataforma\n- Apresentação do trabalho referente ao Módulo 01 \n- Apresentação do trabalho referente ao Módulo 02 \n- Apresentação do Trabalho de Conclusão de Curso\n- Presença na Formatura\nVocê se compromete com você mesma (e conosco) para atender os critérios?": "compromisso_criterios_certificado",
    "Esse curso, tem um valor de mais de R$ 3.500,00 por aluna, pago com tempo e dinheiro das PF doadoras da Fly e PJ parceiras que acreditam na causa. Se você é aceita no Mulheres in Tech da Fly, e se desliga do mesmo por algum motivo, essa vaga e recurso fica perdido. Você está ciente disso?": "ciencia_investimento_vaga",
    "Para a sustentabilidade do Projeto Mulheres in Tech da Fly Educação, estamos convidando as alunas que contam com disponibilidade econômica, a retribuir realizando uma doação mensal voluntária. No seu caso:": "doacao_mensal_voluntaria",
    "Endereço de e-mail": "email",
    "Unnamed: 35": "coluna_vazia"
}

rename_maps["T16"] = {
    "Nome completo": "nome_completo",
    "Qual sua idade?": "idade",
    "Unnamed: 2": "coluna_sem_nome",
    "Como você se identifica?": "raca_etnia",
    "Você faz parte da comunidade LGBTQIAPN+?": "lgbtqia",
    "Qual o seu gênero?": "genero",
    "Qual sua orientação sexual?": "orientacao_sexual",
    "Você é uma pessoa com deficiência?": "pcd",
    "Caso tenha respondido sim anteriormente, nos conte qual o tipo de deficiência que você possui.": "pcd_detalhe",
    "Caso seja uma pessoa com deficiência, nos conte sobre e se ela altera o seu aprendizado e como. Caso não, deixe em branco esta pergunta.": "pcd_detalhe",
    "Você é uma pessoa refugiada?": "refugiada",
    "Caso sim, de qual país você é?": "refugiada_pais",
    "Grau de escolaridade": "escolaridade",
    "Estado que mora:": "estado_residencia",
    "Em qual cidade reside": "cidade_residencia",
    "Como conheceu o Mulheres In Tech e chegou até aqui?": "como_conheceu_mulheres_in_tech",
    "Você já fez outro processo seletivo ou programa na Fly? Se sim, qual?": "processo_seletivo_anterior",
    "Quantas pessoas moram na sua casa? (somente números)": "qtd_pessoas_casa",
    "Renda familiar por pessoa:": "renda_familiar_pessoa",
    "Atualmente você está:": "situacao_profissional_atual",
    "Como funciona a situação financeira na sua casa?": "situacao_financeira_casa",
    "Como você classifica o seu nível de conhecimento na área de probabilidade?": "conhecimento_probabilidade",
    "Você possui alguma evidência para compartilhar conosco que justifique a resposta anterior?": "evidencia_conhecimento_probabilidade",
    "Como você classifica o seu nível de conhecimento na área de estatística?": "conhecimento_estatistica",
    "Você possui alguma evidência para compartilhar conosco que justifique a resposta anterior?.1": "evidencia_conhecimento_estatistica",
    "Como você classifica o seu nível de conhecimento na área de álgebra linear?": "conhecimento_algebra_linear",
    "Você possui alguma evidência para compartilhar conosco que justifique a resposta anterior?.2": "evidencia_conhecimento_algebra_linear",
    "Você possui computador para acompanhar as aulas e realizar a atividades do curso?": "possui_computador",
    "Você possui acesso a Internet?": "possui_internet",
    "O programa inclui mentorias semanais com mulheres que já trabalham na área para lhe ajudar com o conhecimento socioemocional e técnico do programa, como você se vê sendo uma mentorada? Como seria a mentoria ideal para você?": "expectativa_mentoria",
    "É esperado que você estude 10 horas semanais (2h por dia) e, após estudar o conteúdo, conforme surgirem dúvidas, chamar a mentora para lhe ajudar. Como você se percebe pedindo ajuda na sua vida?": "percepcao_pedir_ajuda",
    "Você vai precisar estudar, no mínimo, 2h por dia de forma assíncrona na plataforma. Conte um caso onde você foi autodidata para aprender alguma coisa antes e deu certo :)": "experiencia_autodidata",
    "O programa tem uma duração de 20 semanas. Conte para nós uma experiência positiva onde você tenha iniciado algo e chegado até o fim. Por que você acha que conseguiu finalizar?": "experiencia_positiva_conclusao",
    "Agora, conte para nós uma experiência negativa onde você tenha iniciado alguma atividade e não tenha chegado até o fim, e, por que você acha que não conseguiu chegar até o fim da mesma?": "experiencia_negativa_nao_conclusao",
    "O que acha que mudou de uma a experiência para outra? Porque na primeira foi bem sucedida, e na segunda não?": "diferenca_entre_experiencias",
    "Por que você acredita que vai conseguir chegar ao fim do programa Mulheres in Tech?": "confianca_concluir_programa",
    "A gente sabe que a vida é bem corrida para todos. Então você acha que é sua disponibilidade verdadeira de tempo para estudar e se dedicar ao curso?": "disponibilidade_tempo_estudo",
    "Descreva como é uma semana na sua vida": "rotina_semanal_descricao",
    "Descreva como vai encaixar as 10h de estudo na sua rotina semanal, caso seja aprovada.": "encaixe_horas_estudo_rotina",
    "Se nós lhe perguntássemos, por que deveríamos escolher você diante de outras candidatas, o que você responderia se não tivesse vergonha de responder?": "motivo_escolha_candidata",
    "Para receber o certificado de Formatura do Mulheres in Tech da Fly Educação você precisa preencher os seguintes critérios:\n- 75% de presença nas aulas socioemocionais, ao vivo com camera aberta\n- 100% de conclusão nas aulas científicas, via plataforma\n- Apresentação do trabalho referente ao Módulo 01 \n- Apresentação do trabalho referente ao Módulo 02 \n- Apresentação do Trabalho de Conclusão de Curso\n- Presença na Formatura\nVocê se compromete com você mesma (e conosco) a atender os critérios?": "compromisso_criterios_certificado",
    "Esse curso, tem um valor de mais de R$ 3.500,00 por aluna, pago com tempo e dinheiro das Pessoas Físicas doadoras da Fly e Empresas parceiras que acreditam na causa. Se você for aceita no Mulheres in Tech da Fly, e se desligar do mesmo por algum motivo, essa vaga e recurso ficam perdidos. Você está ciente disso?": "ciencia_investimento_vaga",
    "Para a sustentabilidade do Projeto Mulheres in Tech da Fly Educação, estamos convidando as alunas que contam com disponibilidade econômica, a retribuir a ação realizando uma doação mensal voluntária. No seu caso:": "doacao_mensal_voluntaria"
}

rename_maps["T18"] = {
    "Nome completo": "nome_completo",
    "Qual sua idade?": "idade",
    "Como você se identifica? ": "raca_etnia",
    "Você faz parte da comunidade LGBTQIAPN+?": "lgbtqia",
    "Qual o seu gênero?": "genero",
    "Qual sua orientação sexual?": "orientacao_sexual",
    "Você é uma pessoa com deficiência?": "pcd",
    "Caso tenha respondido sim anteriormente, nos conte qual o tipo de deficiência que você possui.": "pcd_tipo",
    "Caso seja uma pessoa com deficiência, nos conte sobre e se ela altera o seu aprendizado e como. Caso não, deixe em branco esta pergunta.": "pcd_detalhe",
    "Você é uma pessoa refugiada?": "refugiada",
    "Caso sim, de qual país você é?": "refugiada_pais",
    "Grau de escolaridade": "escolaridade",
    "Estado que mora:": "estado_residencia",
    "Column 44": "coluna_sem_nome",
    " Em qual cidade reside": "cidade_residencia",
    "Como conheceu o Mulheres In Tech e chegou até aqui?": "como_conheceu_mulheres_in_tech",
    "Você já fez outro processo seletivo ou programa na Fly? Se sim, qual?": "processo_seletivo_anterior",
    "Quantas pessoas moram na sua casa? (somente números)": "qtd_pessoas_casa",
    "Renda familiar por pessoa:": "renda_familiar_pessoa",
    "Atualmente você está:": "situacao_profissional_atual",
    "Como funciona a situação financeira na sua casa?": "situacao_financeira_casa",
    "Como você classifica o seu nível de conhecimento na área de Inteligência Artificial?": "conhecimento_ia",
    "Você possui alguma evidência para compartilhar conosco que justifique a resposta anterior?": "evidencia_conhecimento_ia",
    "Você possui computador para acompanhar as aulas e realizar a atividades do curso?": "possui_computador",
    "Você possui acesso a Internet?": "possui_internet",
    "O programa inclui mentorias semanais com mulheres que já trabalham na área para lhe ajudar com o conhecimento socioemocional e técnico do programa, como você se vê sendo uma mentorada? Como seria a mentoria ideal para você?": "expectativa_mentoria",
    "É esperado que você estude 10 horas semanais (2h por dia) e, após estudar o conteúdo, conforme surgirem dúvidas, chamar a mentora para lhe ajudar. Como você se percebe pedindo ajuda na sua vida?": "percepcao_pedir_ajuda",
    "Você vai precisar estudar, no mínimo, 2h por dia de forma assíncrona na plataforma. Conte um caso onde você foi autodidata para aprender alguma coisa antes e deu certo :)": "experiencia_autodidata",
    "O programa tem uma duração de 20 semanas. Conte para nós uma experiência positiva onde você tenha iniciado algo e chegado até o fim. Por que você acha que conseguiu finalizar?": "experiencia_positiva_conclusao",
    "Agora, conte para nós uma experiência negativa onde você tenha iniciado alguma atividade e não tenha chegado até o fim, e, por que você acha que não conseguiu chegar até o fim da mesma?": "experiencia_negativa_nao_conclusao",
    "O que acha que mudou de uma a experiência para outra? Porque na primeira foi bem sucedida, e na segunda não?": "diferenca_entre_experiencias",
    "Por que você acredita que vai conseguir chegar ao fim do programa Mulheres in Tech?": "confianca_concluir_programa",
    "A gente sabe que a vida é bem corrida para todos. Então você acha que é sua disponibilidade verdadeira de tempo para estudar e se dedicar ao curso?": "disponibilidade_tempo_estudo",
    "Descreva como é uma semana na sua vida": "rotina_semanal_descricao",
    "Descreva como vai encaixar as 10h de estudo na sua rotina semanal, caso seja aprovada.": "encaixe_horas_estudo_rotina",
    "Se nós lhe perguntássemos, por que deveríamos escolher você diante de outras candidatas, o que você responderia se não tivesse vergonha de responder?": "motivo_escolha_candidata",
    "Para receber o certificado de Formatura do Mulheres in Tech da Fly Educação você precisa preencher os seguintes critérios:\n- 75% de presença nas aulas socioemocionais, ao vivo com camera aberta\n- 100% de conclusão nas aulas científicas, via plataforma\n- Apresentação do trabalho referente ao Módulo 01 \n- Apresentação do trabalho referente ao Módulo 02 \n- Apresentação do Trabalho de Conclusão de Curso\n- Presença na Formatura\nVocê se compromete com você mesma (e conosco) a atender os critérios?": "compromisso_criterios_certificado",
    "Esse curso, tem um valor de mais de R$ 3.500,00 por aluna, pago com tempo e dinheiro das Pessoas Físicas doadoras da Fly e Empresas parceiras que acreditam na causa. Se você for aceita no Mulheres in Tech da Fly, e se desligar do mesmo por algum motivo, essa vaga e recurso ficam perdidos. Você está ciente disso?": "ciencia_investimento_vaga",
    "Para a sustentabilidade do Projeto Mulheres in Tech da Fly Educação, estamos convidando as alunas que contam com disponibilidade econômica, a retribuir a ação realizando uma doação mensal voluntária. No seu caso:": "doacao_mensal_voluntaria"
}

rename_maps["T19"] = {
    "Nome completo": "nome_completo",
    "Qual sua idade?": "idade",
    "Como você se identifica?": "raca_etnia",
    "Você faz parte da comunidade LGBTQIAPN+?": "lgbtqia",
    "Qual o seu gênero?": "genero",
    "Qual sua orientação sexual?": "orientacao_sexual",
    "Você possui filhos ou exerce papel de mãe/cuidadora?": "filhos_cuidadora",
    "Você é uma pessoa com deficiência?": "pcd",
    "Caso tenha respondido sim anteriormente, nos conte qual o tipo de deficiência que você possui.": "pcd_tipo",
    "Caso seja uma pessoa com deficiência, nos conte sobre e se ela altera o seu aprendizado e como. Caso não, deixe em branco esta pergunta.": "pcd_detalhe",
    "Você é uma pessoa refugiada?\nPessoa refugiada é alguém que foi obrigada a deixar seu país de origem por causa de guerras, perseguições, violência ou violações de direitos humanos. Essas pessoas buscam proteção em outro país, como o Brasil, para viver com segurança e dignidade.": "refugiada",
    "Caso sim, de qual país você é?": "refugiada_pais",
    "Grau de escolaridade": "escolaridade",
    "Estado que mora:": "estado_residencia",
    "Em qual cidade reside": "cidade_residencia",
    "Como conheceu o Mulheres In Tech e chegou até aqui?": "como_conheceu_mulheres_in_tech",
    "Você já fez outro processo seletivo ou programa na Fly? Se sim, qual?": "processo_seletivo_anterior",
    "Quantas pessoas moram na sua casa?": "qtd_pessoas_casa",
    "Renda familiar por pessoa:": "renda_familiar_pessoa",
    "Atualmente você está:": "situacao_profissional_atual",
    "Como funciona a situação financeira na sua casa?": "situacao_financeira_casa",
    "Como você classifica o seu nível de conhecimento na área de Inteligência Artificial?": "conhecimento_ia",
    "Você possui alguma evidência para compartilhar conosco que justifique a resposta anterior?": "evidencia_conhecimento_ia",
    "Você possui computador para acompanhar as aulas e realizar a atividades do curso?": "possui_computador",
    "Você possui acesso a Internet?": "possui_internet",
    "O programa inclui mentorias semanais com mulheres que já trabalham na área para lhe ajudar com o conhecimento socioemocional e técnico do programa, como você se vê sendo uma mentorada? Como seria a mentoria ideal para você?": "expectativa_mentoria",
    "É esperado que você estude 10 horas semanais (2h por dia) e, após estudar o conteúdo, conforme surgirem dúvidas, chamar a mentora para lhe ajudar. Como você se percebe pedindo ajuda na sua vida?": "percepcao_pedir_ajuda",
    "Você vai precisar estudar, no mínimo, 2h por dia de forma assíncrona na plataforma. Conte um caso onde você foi autodidata para aprender alguma coisa antes e deu certo :)": "experiencia_autodidata",
    "O programa tem uma duração de 20 semanas. Conte para nós uma experiência positiva onde você tenha iniciado algo e chegado até o fim. Por que você acha que conseguiu finalizar?": "experiencia_positiva_conclusao",
    "Agora, conte para nós uma experiência negativa onde você tenha iniciado alguma atividade e não tenha chegado até o fim, e, por que você acha que não conseguiu chegar até o fim da mesma?": "experiencia_negativa_nao_conclusao",
    "O que acha que mudou de uma a experiência para outra? Porque na primeira foi bem sucedida, e na segunda não?": "diferenca_entre_experiencias",
    "Por que você acredita que vai conseguir chegar ao fim do programa Mulheres in Tech?": "confianca_concluir_programa",
    "A gente sabe que a vida é bem corrida para todos. Então você acha que é sua disponibilidade verdadeira de tempo para estudar e se dedicar ao curso?": "disponibilidade_tempo_estudo",
    "Descreva como é uma semana na sua vida": "rotina_semanal_descricao",
    "Descreva como vai encaixar as 10h de estudo na sua rotina semanal, caso seja aprovada.": "encaixe_horas_estudo_rotina",
    "Se nós lhe perguntássemos, por que deveríamos escolher você diante de outras candidatas, o que você responderia se não tivesse vergonha de responder?": "motivo_escolha_candidata",
    "Para receber o certificado de Formatura do Mulheres in Tech da Fly Educação você precisa preencher os seguintes critérios:\n- 75% de presença nas aulas socioemocionais, ao vivo com camera aberta\n- 100% de conclusão nas aulas científicas, via plataforma\n- Apresentação do trabalho referente ao Módulo 01 \n- Apresentação do trabalho referente ao Módulo 02 \n- Apresentação do Trabalho de Conclusão de Curso\n- Presença na Formatura\nVocê se compromete com você mesma (e conosco) a atender os critérios?": "compromisso_criterios_certificado",
    "Esse curso, tem um valor de mais de R$ 3.500,00 por aluna, pago com tempo e dinheiro das Pessoas Físicas doadoras da Fly e Empresas parceiras que acreditam na causa. Se você for aceita no Mulheres in Tech da Fly, e se desligar do mesmo por algum motivo, essa vaga e recurso ficam perdidos. Você está ciente disso?": "ciencia_investimento_vaga",
    "Para a sustentabilidade do Projeto Mulheres in Tech da Fly Educação, estamos convidando as alunas que contam com disponibilidade econômica, a retribuir a ação realizando uma doação mensal voluntária. No seu caso:": "doacao_mensal_voluntaria"
}

rename_maps["T20"] = {
    "Nome completo": "nome_completo",
    "Qual sua idade?": "idade",
    "Como você se identifica? ": "raca_etnia",
    "Você faz parte da comunidade LGBTQIAPN+?": "lgbtqia",
    "Qual o seu gênero?": "genero",
    "Qual sua orientação sexual?": "orientacao_sexual",
    "Você possui filhos ou exerce papel de mãe/cuidadora? ": "filhos_cuidadora",
    "Você é uma pessoa com deficiência?": "pcd",
    "Caso tenha respondido sim anteriormente, nos conte qual o tipo de deficiência que você possui.": "pcd_tipo",
    "Caso seja uma pessoa com deficiência, nos conte sobre e se ela altera o seu aprendizado e como. Caso não, deixe em branco esta pergunta.": "pcd_detalhe",
    "Você é uma pessoa refugiada?\nPessoa refugiada é alguém que foi obrigada a deixar seu país de origem por causa de guerras, perseguições, violência ou violações de direitos humanos. Essas pessoas buscam proteção em outro país, como o Brasil, para viver com segurança e dignidade.": "refugiada",
    "Caso sim, de qual país você é?": "refugiada_pais",
    "Grau de escolaridade": "escolaridade",
    "Column 49": "coluna_sem_nome",
    "Estado/Região que mora:": "regiao_residencia",
    "Estado que mora:": "estado_residencia",
    " Em qual cidade reside": "cidade_residencia",
    "Como conheceu o Mulheres In Tech e chegou até aqui?": "como_conheceu_mulheres_in_tech",
    "Você já fez outro processo seletivo ou programa na Fly? Se sim, qual?": "processo_seletivo_anterior",
    "Quantas pessoas moram na sua casa? ": "qtd_pessoas_casa",
    "Renda familiar por pessoa:": "renda_familiar_pessoa",
    "Atualmente você está:": "situacao_profissional_atual",
    "Como funciona a situação financeira na sua casa?": "situacao_financeira_casa",
    " Tem interesse em desenvolvimento de Web?": "interesse_dev_web",
    "Você possui alguma evidência para compartilhar conosco que justifique a resposta anterior?": "evidencia_conhecimento_dev_web",
    "Você possui computador para acompanhar as aulas e realizar a atividades do curso?": "possui_computador",
    "Você possui acesso a Internet?": "possui_internet",
    "O programa inclui mentorias semanais com mulheres que já trabalham na área para lhe ajudar com o conhecimento socioemocional e técnico do programa, como você se vê sendo uma mentorada? Como seria a mentoria ideal para você?": "expectativa_mentoria",
    "É esperado que você estude 10 horas semanais (2h por dia) e, após estudar o conteúdo, conforme surgirem dúvidas, chamar a mentora para lhe ajudar. Como você se percebe pedindo ajuda na sua vida?": "percepcao_pedir_ajuda",
    "Você vai precisar estudar, no mínimo, 2h por dia de forma assíncrona na plataforma. Conte um caso onde você foi autodidata para aprender alguma coisa antes e deu certo :)": "experiencia_autodidata",
    "O programa tem uma duração de 23 semanas. Conte para nós uma experiência positiva onde você tenha iniciado algo e chegado até o fim. Por que você acha que conseguiu finalizar?": "experiencia_positiva_conclusao",
    "Agora, conte para nós uma experiência negativa onde você tenha iniciado alguma atividade e não tenha chegado até o fim, e, por que você acha que não conseguiu chegar até o fim da mesma?": "experiencia_negativa_nao_conclusao",
    "O que acha que mudou de uma a experiência para outra? Porque na primeira foi bem sucedida, e na segunda não?": "diferenca_entre_experiencias",
    "Por que você acredita que vai conseguir chegar ao fim do programa Mulheres in Tech?": "confianca_concluir_programa",
    "A gente sabe que a vida é bem corrida para todos. Então você acha que é sua disponibilidade verdadeira de tempo para estudar e se dedicar ao curso?": "disponibilidade_tempo_estudo",
    "Descreva como é uma semana na sua vida": "rotina_semanal_descricao",
    "Descreva como vai encaixar as 10h de estudo na sua rotina semanal, caso seja aprovada.": "encaixe_horas_estudo_rotina",
    "Se nós lhe perguntássemos, por que deveríamos escolher você diante de outras candidatas, o que você responderia se não tivesse vergonha de responder?": "motivo_escolha_candidata",
    "Para receber o certificado de Formatura do Mulheres in Tech da Fly Educação você precisa preencher os seguintes critérios:\n— 75% de presença nas aulas socioemocionais e aulas Tech ao vivo com câmera aberta\n— 75% aulas Tech ao vivo com câmera aberta e 100% de conclusão nas aulas científicas, via plataforma\n— Apresentação do trabalho referente ao Módulo 01 \n— Apresentação do trabalho referente ao Módulo 02 \n— Apresentação do Trabalho de Conclusão de Curso\n— Presença na Formatura\nVocê se compromete com você mesma (e conosco) a atender os critérios?": "compromisso_criterios_certificado",
    "Esse curso, tem um valor de mais de R$ 3.500,00 por aluna, pago com tempo e dinheiro das Pessoas Físicas doadoras da Fly e Empresas parceiras que acreditam na causa. Se você for aceita no Mulheres in Tech da Fly, e se desligar do mesmo por algum motivo, essa vaga e recurso ficam perdidos. Você está ciente disso?": "ciencia_investimento_vaga",
    "Para a sustentabilidade do Projeto Mulheres in Tech da Fly Educação, estamos convidando as alunas que contam com disponibilidade econômica, a retribuir a ação realizando uma doação mensal voluntária. No seu caso:": "doacao_mensal_voluntaria"
}

rename_maps["T22"] = {
    "Nome completo": "nome_completo",
    "Qual a sua data de nascimento?": "data_nascimento",
    "Qual a sua nacionalidade?": "nacionalidade",
    "Qual o seu estado civil?": "estado_civil",
    "Qual o seu endereço completo?  (Por favor, informe dados completos, incluindo: rua/avenida, número, complemento (se houver), bairro, cidade, estado e CEP)": "endereco_completo",
    "Qual a sua profissão?": "profissao",
    "Em relação ao gênero, como você se identifica? ": "genero",
    "Você faz parte da comunidade LGBTQIAPN+ ?": "lgbtqia",
    "Em relação à raça, como você se identifica? ": "raca_etnia",
    "Você é uma pessoa com deficiência ? ": "pcd",
    "Qual é o tipo da sua deficiência?\nEssa informação nos ajuda a garantir acessibilidade durante o curso.": "pcd_tipo",
    "Sua deficiência impacta seu processo de aprendizagem? Se sim, como podemos apoiar você da melhor forma? ": "pcd_impacto_aprendizagem",
    "Há necessidade de adaptações para atividades de aprendizado ou para participação em atividades remotas via computador?": "pcd_necessita_adaptacao",
    "Você é uma pessoa refugiada ou imigrante?": "refugiada_imigrante",
    "Grau de Escolaridade": "escolaridade",
    "Estado de nascimento:": "estado_nascimento",
    "Qual das opções melhor descreve sua relação com Breu Branco? ": "relacao_breu_branco",
    "Como você conheceu o projeto Mulheres In Tech e chegou até aqui? ": "como_conheceu_mulheres_in_tech",
    "Se você conheceu o Mulheres In Tech por meio de parceiros ou indicação, poderia nos contar quem foi? (Nome do parceiro, pessoa ou instituição) ": "como_conheceu_mulheres_in_tech_como_foi",
    "Você já participou de algum outro processo seletivo ou programa oferecido pela Fly Educação? Se sim, conte pra gente qual foi! ": "processo_seletivo_anterior",
    "Quantas pessoas moram na sua casa? (somente números)": "qtd_pessoas_casa",
    "Renda familiar por pessoa:": "renda_familiar_pessoa",
    "Sobre a sua situação profissional atual:": "situacao_profissional_atual",
    "Como está organizada a situação financeira na sua casa atualmente? ": "situacao_financeira_casa",
    "Qual a sua relação atual com o Marketing Digital?": "relacao_marketing_digital",
    "Justifique": "justificativa_interesse",
    "Quais dispositivos com acesso à internet você tem disponíveis em casa?\n(Marque todas as opções que se aplicam)": "dispositivos_disponiveis",
    "Qual é a sua forma mais frequente de acesso à internet?  ": "forma_acesso_internet",
    "O programa oferece mentorias semanais com mulheres que já atuam na área, para apoiar tanto no desenvolvimento técnico quanto socioemocional. Como você se imagina sendo acompanhada/o por uma mentora? O que faria uma mentoria ser ideal para você? ": "expectativa_mentoria",
    "Durante o programa, espera-se uma dedicação média de 11 horas por semana (cerca de 2h30 por dia). Também é importante buscar apoio sempre que surgirem dúvidas, entrando em contato com a mentora.\n\nComo é, para você, o ato de pedir ajuda? Você costuma buscar apoio com facilidade?": "percepcao_pedir_ajuda",
    "Você precisará dedicar cerca de 7 horas por semana para estudar de forma assíncrona (ou seja, no seu próprio tempo, sem horários fixos) na plataforma.\n\nConte-nos uma experiência em que você aprendeu algo por conta própria e deu certo. Como foi esse processo?": "experiencia_autodidata",
    "O curso dura 2,5 meses. Conte-nos uma experiência em que você começou algo e foi até o fim. O que te ajudou a chegar lá? ": "experiencia_positiva_conclusao",
    "Agora, conte-nos uma experiência em que você começou algo, mas não conseguiu concluir. O que aconteceu nesse processo?": "experiencia_negativa_nao_conclusao",
    "O que você acredita que foi diferente entre as duas experiências? O que te ajudou a concluir uma delas e o que dificultou a outra? ": "diferenca_entre_experiencias",
    "O que te dá confiança de que vai conseguir chegar até o fim desse programa? ": "confianca_concluir_programa",
    "Sabemos que a rotina pode ser corrida. Qual é, de forma realista, o tempo que você tem disponível para se dedicar aos estudos durante o curso? ": "disponibilidade_tempo_estudo",
    "Como é a sua semana no dia a dia? ": "rotina_semanal_descricao",
    "Caso seja aprovada, como você pretende organizar sua rotina para incluir as 11 horas semanais de estudo do curso? ": "encaixe_horas_estudo_rotina",
    "Por que você acredita que deve ser escolhida para esta vaga, mesmo diante de tantas outras mulheres incríveis? Responda com o máximo de sinceridade que conseguir.": "motivo_escolha_candidata",
    "Para receber o certificado de formatura do Mulheres in Tech da Fly Educação, é necessário cumprir os seguintes critérios:\n- Participar de pelo menos 75% das aulas ao vivo (socioemocionais e de mercado);\n- Concluir 100% das aulas na plataforma;\n- Entregar o Trabalho de Conclusão de Curso (TCC);\n- Estar presente na cerimônia de formatura.\nVocê está comprometida consigo mesma (e com a gente) a cumprir esses critérios até o final do programa?": "compromisso_criterios_certificado",
    "Este curso representa um investimento de mais de R$ 3.500,00 por participante, viabilizado por pessoas físicas doadoras e instituições parceiras que acreditam na causa.\nSe você for aceita no programa e desistir ao longo do curso, essa vaga, e o recurso investido, não poderão ser redistribuídos.\nVocê está ciente e comprometida com essa responsabilidade?": "ciencia_investimento_vaga",
    "Para apoiar a continuidade do Projeto Mulheres in Tech da Fly Educação, estamos fazendo um convite opcional às participantes que tenham alguma disponibilidade financeira: contribuir com uma doação mensal voluntária, no valor que for possível para você.\nNo seu caso:": "doacao_mensal_voluntaria",
    "Sobre sua carreira profissional, você está:": "situacao_carreira_atual",
    "Você concluiu (ou está cursando) seus estudos com apoio de políticas públicas?\nExemplos: escola pública, cotas, bolsa permanência, Prouni, FIES, etc.": "apoio_politicas_publicas",
    "Você já teve que interromper os estudos em algum momento?\nPode ser por motivos de trabalho, cuidado com a família, saúde, entre outros.": "interrupcao_estudos"
}

rename_maps["T23"] = {
    "Nome completo": "nome_completo",
    "Endereço completo:\nPor favor, informe dados completos, incluindo: rua/avenida, número, complemento (se houver), bairro, cidade, estado, CEP": "endereco_completo",
    "Qual a sua ocupação?": "ocupacao",
    "Data de nascimento": "data_nascimento",
    "Você é uma pessoa refugiada ou imigrante?": "refugiada_imigrante",
    "Nacionalidade": "nacionalidade",
    "Em relação ao gênero, como você se identifica? ": "genero",
    "Em relação à raça, como você se identifica? ": "raca_etnia",
    "Você faz parte da comunidade LGBTQIA+?\nLembramos que a turma é EXCLUSIVA para mulheres pertencentes à comunidade LGBTQIAPN+.": "lgbtqia",
    " Qual é o seu nível de escolaridade?  ": "escolaridade",
    " Qual é a renda familiar aproximada por pessoa na sua casa?  ": "renda_familiar_pessoa",
    "Você estudou principalmente em:  ": "tipo_escola_formacao",
    "Qual é sua situação profissional atualmente?  ": "situacao_profissional_atual",
    "Quanto tempo você consegue dedicar ao curso por semana?  ": "disponibilidade_tempo_curso",
    "Qual dispositivo você pretende usar para acompanhar o curso?  ": "dispositivos_disponiveis",
    " Qual frase melhor descreve sua experiência com programação?  ": "experiencia_programacao",
    "Se você já programou, qual linguagem utilizou com mais frequência?  ": "linguagem_programacao",
    "Em algum momento você já trabalhou com dados (planilhas, análise ou programação)?": "experiencia_dados",
    "Imagine que você recebeu um dataset com informações incompletas ou inconsistentes.\nQual seria sua primeira ação?  ": "dataset_inconsistente_acao",
    "Qual dessas bibliotecas ou ferramentas você já utilizou em algum projeto ou estudo?  ": "bibliotecas_ferramentas_utilizadas",
    "Você já utilizou Git ou GitHub em algum projeto?  ": "git_github_uso",
    "Se você tiver, compartilhe um link para algum projeto ou perfil técnico  ": "link_projeto_perfil",
    "Descreva brevemente um projeto ou exercício técnico que você já fez ou gostaria de fazer na área de dados ou IA.  ": "projeto_dados_ia_descricao",
    " OPCIONAL: Um dataset mostra que a taxa de evasão de um curso foi de 20% na turma A e 10% na turma B. O que isso indica sobre as duas turmas?  ": "dataset_evasao_interpretacao",
    "Para receber o certificado do projeto Mulheres In Tech versão Data Science & IA LGBTQIA+  da Fly Educação, você precisará preencher os seguintes critérios:\n- Ter, no mínimo, 75% de presença nas aulas socioemocionais com câmera aberta e interação nas atividades;\n- Ter, no mínimo, 100% de presença nas aulas científicas com câmera aberta e interação nas atividades;\n- Apresentar 100% dos trabalhos solicitados no programa, dentre eles os de conclusão dos módulos socioemocionais e as atividades semanais;\n- Ter 100% de conclusão das atividades do conteúdo científico;\n- Apresentar o Trabalho de Conclusão de Curso e ser aprovada pela banca examinadora;\n- Estar presente na Formatura;\n- Gravar vídeo depoimento no início do curso e ao término da formação.\n\nVocê está comprometida consigo mesma (e com a gente) a cumprir esses critérios até o final do programa?\n": "compromisso_criterios_certificado",
    "Este curso representa um investimento dos nossos patrocinadores por participante, viabilizado por pessoas físicas doadoras e instituições parceiras que acreditam na causa.\nSe você for aceita no programa e desistir ao longo do curso, essa vaga e o recurso investido não poderão ser redistribuídos.\nVocê está ciente e comprometida com essa responsabilidade?": "ciencia_investimento_vaga",
    "A leitura do edital é obrigatória.\nVocê leu o Edital?": "leitura_edital"
}
